[
  {# index 0. for eeg preprocessing
    "path_dir": "../data/derivatives/eeglab/",
    "fname_eeg": "sub-38_task-rsvp_continuous.set",
    "fname_save": "sub-38_power.binary",
    "frequencies":[7, 30, 1], #eeg time-frequency analysis. with np.arange()
    "tmin":-0.1, #eeg time-frequency analysis. min time. in msec
    "tmax": 1.0, #eeg time-frequency analysis. max time. in msec
    "ind_event": 1, #stimulus onset of this dataset.
    "flag_num_powers": True, #whether restricting the number of epoches
    "num_powers": 10 #the number of epoches (used in spatiotemporal)
  },

 {#index 1. for image loading and eeg roi extraction
    "fname_imglist": "../data/sub-38/sub-38_eeg_sub-38_task-rsvp_events.csv",
    "range_roi": 3, # in cell
    "start_roi": 0 # in cell
 },

  {#index 2. for dnn model parameters
      "module_path": "https://tfhub.dev/deepmind/bigbigan-resnet50/1" #Pretrained BigBiGAN
    }

]